seed = 47

image_path = "./test_dataset"
meta_path = "cache"
skip_prepare_image = false

vae_path = "https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors"
vae_dtype = "fp16"

model_path = "models/AOM3B2_orangemixs_fp16"
save_dir = "./out"

optimizer = "adamW8bit"

model_name = "creative-test"

mode = 'lokr'

n_epochs = 50
batch_size = 1
gradient_accumulation_steps = 1

save_every_n_epochs = 1
save_every_n_steps = 5

preview_every_n_epochs = 1
preview_every_n_steps = 100

mixed_precision = "fp16"
weight_dtype = "fp32"
save_dtype = "fp16"

unet_lr = 1e-4
optimizer_warmup_steps = 100
optimizer_num_cycles = 10

text_encoder_lr = 0

noise_offset = 0.1

snr_gamma = 5.0

max_grad_norm = 1.0

timestep_bias_strategy = "uniform"

use_ema = false

gradient_checkpointing = true


[[preview_sample_options]]
prompt = "1girl, blonde_hair, armor, weapon, blood, gauntlets, sword, rain, blue_eyes, blood_on_face, excalibur_(fate/stay_night), lips, armored_dress, holding, holding_weapon, realistic, solo"
negative_prompt = "worst quality, bad quality, blurry, low resolution"
seed = 47
steps = 25
