seed = 47

image_path = "./test_dataset"
meta_path = "cache"
skip_prepare_image = false

vae_path = "https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors"
vae_dtype = "fp16"

model_path = "models/AOM3B2_orangemixs_fp16"
save_dir = "./out"

optimizer = "adamW8bit"

model_name = "creative-test"

mode = 'full-finetune'

n_epochs = 50
batch_size = 8
gradient_accumulation_steps = 4 # 增加梯度累积步数

save_every_n_epochs = 999
save_every_n_steps = 500

preview_every_n_epochs = 999
preview_every_n_steps = 500

mixed_precision = "bf16"
weight_dtype = "fp32"
save_dtype = "fp16"

unet_lr = 1e-4
optimizer_warmup_steps = 100
optimizer_num_cycles = 10

text_encoder_lr = 0

noise_offset = 0.1

snr_gamma = 5.0

max_grad_norm = 1.0

timestep_bias_strategy = "uniform"

use_ema = false

gradient_checkpointing = true

zero_grad_set_to_none = true # 设置为true以减少内存使用

# # 增加lokr_factor以减少训练参数
# lokr_factor = 32  # 从16增加到32

[[preview_sample_options]]
prompt = "1girl, blonde_hair, armor, weapon, blood, gauntlets, sword, rain, blue_eyes, blood_on_face, excalibur_(fate/stay_night), lips, armored_dress, holding, holding_weapon, realistic, solo"
negative_prompt = "worst quality, bad quality, blurry, low resolution"
seed = 47
steps = 25
