seed = 47
use_enhanced_embeddings = true

model_path = "models/AOM3B2_orangemixs_fp16"
save_dir = "./out/sample15"
model_name = "sample15"

meta_path = ".dt_cache/sample_dataset"
skip_prepare_image = false

vae_path = "https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors"
vae_dtype = "bf16"

all_tags_dropout = 0.1
single_tag_dropout = 0.1


optimizer = "adamW8bit"

mode = 'lokr'

n_epochs = 50
batch_size = 1
gradient_accumulation_steps = 1 # 增加梯度累积步数

save_every_n_epochs = 0
save_every_n_steps = 500

preview_every_n_epochs = 0
preview_every_n_steps = 50
preview_before_training = true

checkpoint_every_n_steps = 50

mixed_precision = "bf16"
weight_dtype = "fp32"
save_dtype = "fp16"

unet_lr = 2e-5
optimizer_warmup_steps = 50
optimizer_num_cycles = 4

text_encoder_lr = 0

noise_offset = 0.1
input_perturbation = 0.1

snr_gamma = 5.0

max_grad_norm = 1.0

timestep_bias_strategy = "logit"
use_ema = false

gradient_checkpointing = true

zero_grad_set_to_none = true

# # 增加lokr_factor以减少训练参数
# lokr_factor = 32  # 从16增加到32

enable_flash_attention = true

[[preview_sample_options]]
prompt = "1girl, breasts, solo, underwear, large_breasts, ahoge, short_hair, bra, yellow_eyes, looking_at_viewer, blush, grey_hair, cleavage, lying, fur_trim, on_back, black_bra, long_sleeves, collarbone, coat, jacket, closed_mouth, fur-trimmed_coat, open_clothes, hands_on_own_chest, jeanne_d'arc_alter_(fate), jeanne_d'arc_alter_(ver._shinjuku_1999)_(fate)"
negative_prompt = "worst quality, bad quality, blurry, low resolution"
seed = 47
steps = 25
width = 768
height = 768
clip_skip = 2
