seed = 47

# image_path = "/home/jannchie/SimpleTuner/datasets/suzume"
meta_path = "demo_meta"
skip_prepare_image = true

vae_path = "madebyollin/sdxl-vae-fp16-fix"
vae_dtype = "fp16"

model_path = "../SimpleTuner/models/creative-xl-0.9-b2"
save_dir = "./out"

# ss_meta_path = "E:/dataset-demo/meta.json"

# if dataset_path is not set, it will use the dataset_meta_path folder.
# dataset_path = "E:/dataset-demo"

optimizer = "adamW8bit"

model_name = "creativexl-test"

mode = 'lokr'

n_epochs = 50
batch_size = 1
gradient_accumulation_steps = 1

save_every_n_epochs = 1
save_every_n_steps = 2000

preview_every_n_epochs = 1
preview_every_n_steps = 1000

mixed_precision = "bf16"
weight_dtype = "bf16"
save_dtype = "fp16"

unet_lr = 5e-4

text_encoder_1_lr = 0
text_encoder_2_lr = 0

# lora_rank = 4
# lora_alpha = 1
# lokr_factor = 16

noise_offset = 0.0

snr_gamma = 5.0

max_grad_norm = 1.0

timestep_bias_strategy = "none"
timestep_bias_portion = 0.25
timestep_bias_begin = 0
timestep_bias_end = 100

use_ema = false

gradient_checkpointing = true

# log_with = "wandb"

# prediction_type = 'v_prediction'

[[preview_sample_options]]
prompt = "background, cityscape, urban, city, street, road, buildings, cars, traffic, night, star, cloud"
negative_prompt = "worst quality, bad quality, blurry, low resolution"
seed = 47
steps = 25
