seed = 47
use_enhanced_embeddings = false

image_path = "/home/jannchie/SimpleTuner/datasets/suzume"

dataset_path = "datasets/suzume_xl"

vae_path = "madebyollin/sdxl-vae-fp16-fix"
vae_dtype = "fp16"

model_path = "../SimpleTuner/models/creative-xl-0.9-b2"
save_dir = "./out"

optimizer = "adafactor"

model_name = "creativexl-test-xl"

mode = 'full-finetune'
# mode = 'lokr'

n_epochs = 50
batch_size = 1
gradient_accumulation_steps = 1

save_every_n_epochs = 1
save_every_n_steps = 5

preview_every_n_epochs = 1
preview_every_n_steps = 100

mixed_precision = "bf16"
weight_dtype = "fp32"
save_dtype = "fp16"

unet_lr = 1e-4
optimizer_warmup_steps = 100
optimizer_num_cycles = 10

text_encoder_1_lr = 0
text_encoder_2_lr = 0

noise_offset = 0.1
input_perturbation = 0.1

timestep_bias_strategy = "logit"
gradient_checkpointing = true


[[preview_sample_options]]
prompt = "background, cityscape, urban, city, street, road, buildings, cars, traffic, night, star, cloud"
negative_prompt = "worst quality, bad quality, blurry, low resolution"
seed = 47
steps = 25
clip_skip = 2
