seed = 47


dataset_path = ".dt_cache/suzume"

vae_path = "madebyollin/sdxl-vae-fp16-fix"
vae_dtype = "fp16"

model_path = "cagliostrolab/animagine-xl-3.1"
save_dir = "./out"

optimizer = "adamW8bit"
model_name = "suzume-lora"

mode = 'lokr'
lora_dim = 2
lora_alpha = 1
conv_dim = 4
conv_alpha = 1

n_epochs = 50
batch_size = 1
gradient_accumulation_steps = 1

input_perturbation = 0.01
use_multires_noise = true

save_every_n_epochs = 1
save_every_n_steps = 0

preview_every_n_epochs = 1
preview_every_n_steps = 0

mixed_precision = "bf16"
weight_dtype = "fp32"
save_dtype = "fp16"

unet_lr = 1e-4
snr_gamma = 5.0
optimizer_warmup_steps = 0
optimizer_num_cycles = 4

text_encoder_1_lr = 0
text_encoder_2_lr = 0

timestep_bias_strategy = "logit"
gradient_checkpointing = true


[[preview_sample_options]]
prompt = "best quality, high quality, moon, night, sky, scenery, cloud, no_humans, outdoors, ocean, night_sky, full_moon, horizon, water, cloudy_sky, star_(sky), blue_theme"
negative_prompt = "worst quality, bad quality, blurry, low resolution"
seed = 47
steps = 25
